### ISSUE TITLE
502 bad gateway using type-graphql

### ISSUE THREAD

**Issue by louisholley** [michalkvasnicak/aws-lambda-graphql#137]
We've recently refactored our backend to use type-graphql which needs to build the schema before calling `new Server` so we've ended up with something like this:

```
exports.handleWebSocket = (
  event: APIGatewayWebSocketEvent,
  context: LambdaContext
) => {
  createServer()
    .then(async server => {
      const handler = server.createWebSocketHandler();
      return handler(event, context);
    })
    .catch(err => {
      console.error(err);
      throw 'failed to start websocket handler';
    });
};
```

trying to subscribe from the client was giving me 502 errors from the websocket requests...

the args are logging out fine in cloudwatch so it's definitely being executed. my serverless.yml looks like this:
```
functions:
  wsHandler:
    handler: serverNew.handleWebSocket
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
```

using the standard docs version of `exports.handleWebSocket = server.createWebSocketHandler()` works fine, but we can't do this as the schema isn't available until the function `createServer` above finishes. I've run out of ideas for how to debug this let alone fix it...has anyone experienced something similar? I'd be infinitely grateful for some help!
