### ISSUE TITLE
[LocalStack] - GraphQL Playground is not able to run subscription

### ISSUE THREAD

**Issue by raheelkhan** [michalkvasnicak/aws-lambda-graphql#69]
I am trying this library and so far its all good for `Queries` and `Mutation`. However the real reason I am trying this library is to work with GraphQL subscription in Serverless.

So after running this server, If i try to connect via google console a raw ws connection `var socket = new WebSocket("ws://localhost:3001");`, It saves a record in DynamoDB Connections table.

However, from GraphQL playground, running the subscription, it goes to listening mode forever, but there is no effect on the server.

Please advise.

Thanks

**Comment by michalkvasnicak** [comment]
@raheelkhan could please provide how you test it.

1. you use playground to connect to this endpoint and listen to subscription (if listening mode runs then this part is ok)
2. do you fire some action using Mutation to publish events?

I don't understand what effect should be visible on server. Could you please explain it?

**Comment by raheelkhan** [comment]
Hi @michalkvasnicak 

Thanks for your reply. 
Let me try to explain you steps.

My server is running as per the documentation in this repository.

```
Serverless: Offline [HTTP] listening on http://localhost:3000
Serverless: Offline [websocket] listening on ws://localhost:3001
```

My serverless.yml looks like 

```
functions:
  httpHandler:
    handler: graphql.handleHTTP
    events:
      - http:
          path: /
          method: any
          cors: true
  wsHandler:
    handler: graphql.handleWebSocket
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
  eventProcessorHandler:
    handler: graphql.handleEvents
    events:
      - stream:
          enabled: true
          type: dynamodb
          arn:
            Fn::GetAtt: [EventsDynamoDBTable, StreamArn]
```

If i open GraphQL playground at `http://localhost:3000`, I can successfully speak with the server and do queries and mutations. In my mutation I am also publishing and I can verify this in the DynamoDB `Events` table which class `DynamoDBEventStore` uses.

```
export const createSomething = async (
	_: any,
	{ foo, bar }: FooBar,
	{
		dataSources,
		pubsub
	}: { dataSources: { baz: BazApi }; pubsub: PubSub }
) => {
	const response = await dataSources.baz.createSomething(
		foo as Foo,
		bar as Bar
	);

	await pubsub.publish(SOMETHING_CREATED, response);

	return response;
};
```

The problem is if i open GraphQL Playground in two browsers, Run subscription in one browser so that it goes to listening... mode and run mutation in the other browser.

My expectation is that the `Connections`, `Subscriptions` and `SubscriptionOperations` table in Dynamodb should be populated by this time with a record based on one client is on listening mode.

However, that listening mode stays as it is forever. However, I see one record populated in the `Events` table.

Please let me know if you have more questions. I know I am not able to put properly into words the problem.
