### ISSUE TITLE
Provide/Document API Gateway v2 configuration

### ISSUE THREAD

**Issue by ebarault** [michalkvasnicak/aws-lambda-graphql#75]
Hi, many thanks for your implementation

Unless i missed it, i could not find details on the AWS API Gateway v2 configuration in the chat example (doc, severless config, cf config)

Could you describe the configuration you used in the example ?

**Comment by michalkvasnicak** [comment]
@ebarault the configuration is handled by `serverless`. Please see https://github.com/michalkvasnicak/aws-lambda-graphql/blob/master/packages/chat-example-server/serverless.yml#L76 where websocket routes are defined.

**Comment by michalkvasnicak** [comment]
Also there is a cloudformation template but I think it's really outdated and at the time when I created this library it wasn't possible to use cloudformation for Api gateway v2.

**Comment by ebarault** [comment]
@michalkvasnicak i can see the definition of the routes, but it did not realized this was enough with serverless to trigger the websocket apigw creation.
```
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default
```
I was expecting a dedicated configuration stating the "Route Selection Expression" expression.
Could you tell me from aws gui, what is the value for the param ?
