### ISSUE TITLE
Question: behavior of the socket after running serverless deploy

### ISSUE THREAD

**Issue by IslamWahid** [michalkvasnicak/aws-lambda-graphql#76]
I have a question I managed to set up everything on the server-side as the example tested that locally and also after deployment to AWS using serverless with apollo playground and everything was fine.

but I was trying to deploy while there's a subscription on the apollo playground to see how it would react in this case and found that the playground isn't getting any disconnect event to close the socket.

the connection is still open but not getting any new events. I checked the dynamoDb tables the subscriptions and subscriptionsOperations are getting empty after a few mins of the deployment and the rest still not affected.

Don't know if there's something I should implement to handle this or this is not handled by the apollo playground.

here are more details on my code:

**serverless.yml**
```
functions:
  webSocketHandler:
    handler: dist/src/index.webSocketHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

  dynamoDBStreamHandler:
    handler: dist/src/index.dynamoDBStreamHandler
    events:
      - stream:
          enabled: true
          type: dynamodb
          arn:
            Fn::GetAtt: [EventsDynamoDBTable, StreamArn]

  graphqlHttpHandler:
    handler: dist/src/index.graphqlHandler
    events:
      - http:
          path: graphql
          method: any
          cors: true
```
**package.json**
```
"dependencies": {
    "apollo-server-lambda": "^2.9.3",
    "aws-lambda-graphql": "^1.0.0-alpha.4",
    "aws-sdk": "^2.589.0",
    "graphql": "^14.0.2",
    "graphql-subscriptions": "^1.1.0",
  }
```
**subscription.ts**
```typescript
import {
  DynamoDBConnectionManager,
  DynamoDBEventProcessor,
  DynamoDBEventStore,
  DynamoDBSubscriptionManager,
  PubSub,
} from 'aws-lambda-graphql';
import { ApiGatewayManagementApi, DynamoDB } from 'aws-sdk';
import config from '@config';

const env = config.get('env');
const postfix = `metatrust-service-${env}`;

const eventsTable = `Events-${postfix}`;
const subscriptionsTable = `Subscriptions-${postfix}`;
const subscriptionOperationsTable = `SubscriptionOperations-${postfix}`;
const connectionsTable = `Connections-${postfix}`;

const dynamoDbClient = new DynamoDB.DocumentClient({
  ...(process.env.IS_OFFLINE
    ? {
        endpoint: 'http://localhost:8000',
      }
    : {}),
});
const eventStore = new DynamoDBEventStore({
  dynamoDbClient,
  eventsTable,
});

export const pubSub = new PubSub({ eventStore });
export const subscriptionManager = new DynamoDBSubscriptionManager({
  dynamoDbClient,
  subscriptionsTableName: subscriptionsTable,
  subscriptionOperationsTableName: subscriptionOperationsTable,
});
export const connectionManager = new DynamoDBConnectionManager({
  apiGatewayManager: process.env.IS_OFFLINE
    ? new ApiGatewayManagementApi({
        endpoint: 'http://localhost:3002',
      })
    : undefined,
  dynamoDbClient,
  subscriptions: subscriptionManager,
  connectionsTable,
});
export const eventProcessor = new DynamoDBEventProcessor();

```

### Update:

- after testing this with client implementation on staging environment I tried to deploy it when there're some open connections and it was handled perfectly with the AWS gateway.
